### ISSUE TITLE
Issue running with Python 2.7 

### ISSUE THREAD

**Issue by jd12** [TravisToolbox/pycodestyle-travis#1]
Hey, 

I'm not sure if I'm running this correctly. I have some files that I'm trying to check with Python 2.7 but they keep getting skipped 

OS: Ubuntu 16.04 (through Vagrant / VirtualBox)
Python version: 2.7.12 

This is the travis.yml file I'm using 

```
sudo: required

matrix:
  include:
    - language: python
      python: 2.7.12
      os: linux
      before_install:
        - pip install --upgrade setuptools
        - git clone https://github.com/TravisToolbox/pycodestyle-travis.git
      install:
        - "./pycodestyle-travis/install.sh"
      script:
        - "./pycodestyle-travis/scan.sh"
```
This is my printout on Travis 
![screen shot 2019-01-12 at 10 21 29 am](https://user-images.githubusercontent.com/5401810/51076927-e1eccd00-1653-11e9-81f6-5499fc0fda72.png)

[Here](https://github.com/ChadwickSchool/oe-group-maker/tree/development) is my repository if that helps 

Any help would be greatly appreciated
